'use client';

import Icon from '@/components/ui/icon';
import { useBulkSelection } from '../hooks/use-bulk-selection';
import type { ComplianceDocument, DocumentCategory, DocumentStatus } from '../types/administration';

const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat('vi-VN').format(new Date(date + 'T00:00:00')) : 'Không thời hạn';
const statusLabels: Record<DocumentStatus, string> = { DRAFT: 'Nháp', ACTIVE: 'Hiệu lực', EXPIRED: 'Hết hạn', RENEWING: 'Đang gia hạn', REVOKED: 'Thu hồi' };
const categoryLabels: Record<DocumentCategory, string> = { INSURANCE: 'Bảo hiểm', FIRE_SAFETY: 'PCCC & an toàn', LICENSE: 'Giấy phép', INSPECTION: 'Kiểm định', CONTRACT: 'Hợp đồng', CERTIFICATE: 'Chứng chỉ', OTHER: 'Khác' };
const expiryLabels: Record<string, string> = { ACTIVE: 'Còn hiệu lực', EXPIRING: 'Sắp hết hạn', EXPIRED: 'Đã hết hạn', NO_EXPIRY: 'Không thời hạn', DRAFT: 'Nháp', REVOKED: 'Thu hồi' };

export default function DocumentDataTable({ rows, canManage, busy, edit, remove, removeSelected }: { rows: ComplianceDocument[]; canManage: boolean; busy: string; edit: (item: ComplianceDocument) => void; remove: (item: ComplianceDocument) => Promise<void>; removeSelected: (ids: string[]) => Promise<boolean> }) {
  const selection = useBulkSelection(rows);
  async function bulkDelete() { if (await removeSelected(selection.selectedIds)) selection.clear(); }
  return <section className="admin-data-card"><header><div><h2>Sổ theo dõi giấy tờ</h2><p>{rows.length} hồ sơ theo bộ lọc hiện tại</p></div>{canManage && selection.selectedCount > 0 && <div className="bulk-delete-toolbar"><span>Đã chọn <b>{selection.selectedCount}</b></span><button className="nova-button danger" disabled={busy === 'bulk-documents'} onClick={() => void bulkDelete()}><Icon name="trash" />{busy === 'bulk-documents' ? 'Đang xóa…' : 'Xóa đã chọn'}</button></div>}</header><div className="admin-table-wrap"><table className="admin-table document-table"><thead><tr><th className="selection-column">{canManage && <input type="checkbox" aria-label="Chọn tất cả giấy tờ đang hiển thị" checked={selection.allSelected} onChange={selection.toggleAll} />}</th><th>Giấy tờ</th><th>Loại</th><th>Phòng ban / đơn vị</th><th>Hiệu lực</th><th>Hết hạn</th><th>Cảnh báo</th><th>Trạng thái</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className={selection.selected.has(item.id) ? 'selected-row' : ''}><td className="selection-column">{canManage && <input type="checkbox" aria-label={`Chọn ${item.documentName}`} checked={selection.selected.has(item.id)} onChange={() => selection.toggle(item.id)} />}</td><td><b>{item.documentName}</b><small>{item.documentNo}</small></td><td>{item.documentTypeName}<small>{categoryLabels[item.documentCategory] || item.documentCategory}</small></td><td><b>{item.businessUnitName || 'Chưa xác định'}</b><small>{item.responsibleEmployeeName || item.issuedBy || '—'}</small></td><td>{formatDate(item.effectiveOn || item.issuedOn)}</td><td><b>{formatDate(item.expiresOn)}</b><small>Nhắc trước {item.reminderDaysBefore} ngày</small></td><td><em className={`expiry ${item.expiryState.toLowerCase()}`}>{expiryLabels[item.expiryState] || item.expiryState}{item.daysRemaining !== null && ` · ${item.daysRemaining} ngày`}</em></td><td><em className={`status ${item.status.toLowerCase()}`}>{statusLabels[item.status]}</em></td><td>{canManage && <div className="admin-row-actions"><button onClick={() => edit(item)} aria-label="Sửa"><Icon name="edit" /></button><button className="danger" disabled={busy === item.id} onClick={() => void remove(item)} aria-label="Xóa"><Icon name="trash" /></button></div>}</td></tr>)}</tbody></table>{!rows.length && <div className="admin-empty">Chưa có giấy tờ phù hợp.</div>}</div></section>;
}
