import type { ApiRequestOptions } from '@/lib/api/client';
import type { AdministrativeImportPreview, AdministrativeImportResult, BulkDeleteResult, BusinessUnit, ComplianceDocument, DocumentDashboard, DocumentInput, DocumentType, Expense, ExpenseBranch, ExpenseBranchInput, ExpenseCategory, ExpenseDashboard, ExpenseDepartment, ExpenseDepartmentInput, ExpenseInput, ExpenseInvoice, ExpenseItem, ExpenseItemInput } from '../types/administration';
type Request = <T>(path: string, options?: ApiRequestOptions) => Promise<T>;
const query = (values: Record<string, string>) => { const result = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => value && result.set(key, value)); return result.toString(); };
export const listBusinessUnits = (request: Request) => request<BusinessUnit[]>('/api/admin/reference/business-units');
export const listExpenseBranches = (request: Request, includeInactive = false) => request<ExpenseBranch[]>(`/api/admin/reference/expense-branches?includeInactive=${includeInactive}`);
export const listExpenseDepartments = (request: Request, includeInactive = false) => request<ExpenseDepartment[]>(`/api/admin/reference/expense-departments?includeInactive=${includeInactive}`);
export const listExpenseItems = (request: Request, includeInactive = false) => request<ExpenseItem[]>(`/api/admin/reference/expense-items?includeInactive=${includeInactive}`);
export const createExpenseBranch = (request: Request, body: ExpenseBranchInput) => request<ExpenseBranch>('/api/admin/expense-branches', { method: 'POST', body });
export const updateExpenseBranch = (request: Request, id: string, body: ExpenseBranchInput) => request<ExpenseBranch>(`/api/admin/expense-branches/${id}`, { method: 'PUT', body });
export const deleteExpenseBranch = (request: Request, id: string) => request<void>(`/api/admin/expense-branches/${id}`, { method: 'DELETE' });
export const createExpenseDepartment = (request: Request, body: ExpenseDepartmentInput) => request<ExpenseDepartment>('/api/admin/expense-departments', { method: 'POST', body });
export const updateExpenseDepartment = (request: Request, id: string, body: ExpenseDepartmentInput) => request<ExpenseDepartment>(`/api/admin/expense-departments/${id}`, { method: 'PUT', body });
export const deleteExpenseDepartment = (request: Request, id: string) => request<void>(`/api/admin/expense-departments/${id}`, { method: 'DELETE' });
export const createExpenseItem = (request: Request, body: ExpenseItemInput) => request<ExpenseItem>('/api/admin/expense-items', { method: 'POST', body });
export const updateExpenseItem = (request: Request, id: string, body: ExpenseItemInput) => request<ExpenseItem>(`/api/admin/expense-items/${id}`, { method: 'PUT', body });
export const deleteExpenseItem = (request: Request, id: string) => request<void>(`/api/admin/expense-items/${id}`, { method: 'DELETE' });
export const listExpenseCategories = (request: Request) => request<ExpenseCategory[]>('/api/admin/expense-categories?includeInactive=true');
export const createExpenseCategory = (request: Request, body: Omit<ExpenseCategory, 'id' | 'parentName'>) => request<ExpenseCategory>('/api/admin/expense-categories', { method: 'POST', body });
export const updateExpenseCategory = (request: Request, id: string, body: Omit<ExpenseCategory, 'id' | 'parentName'>) => request<ExpenseCategory>(`/api/admin/expense-categories/${id}`, { method: 'PUT', body });
export const deleteExpenseCategory = (request: Request, id: string) => request<void>(`/api/admin/expense-categories/${id}`, { method: 'DELETE' });
export const listExpenses = (request: Request, filters: Record<string, string>) => request<Expense[]>(`/api/admin/expenses?${query(filters)}`);
export const getExpenseDashboard = (request: Request, filters: Record<string, string>) => request<ExpenseDashboard>(`/api/admin/expenses/dashboard?${query(filters)}`);
export const createExpense = (request: Request, body: ExpenseInput) => request<Expense>('/api/admin/expenses', { method: 'POST', body });
export const updateExpense = (request: Request, id: string, body: ExpenseInput) => request<Expense>(`/api/admin/expenses/${id}`, { method: 'PUT', body });
export const setExpenseActualAsPlanned = (request: Request, id: string) => request<Expense>(`/api/admin/expenses/${id}/actual-as-planned`, { method: 'PATCH' });
export const deleteExpense = (request: Request, id: string) => request<void>(`/api/admin/expenses/${id}`, { method: 'DELETE' });
export const deleteExpenses = (request: Request, ids: string[]) => request<BulkDeleteResult>('/api/admin/expenses/bulk-delete', { method: 'POST', body: { ids } });
export const listExpenseInvoices = (request: Request, expenseId: string) => request<ExpenseInvoice[]>(`/api/admin/expenses/${expenseId}/invoices`);
export const uploadExpenseInvoice = (request: Request, expenseId: string, file: File) => { const body = new FormData(); body.set('file', file); return request<ExpenseInvoice>(`/api/admin/expenses/${expenseId}/invoices`, { method: 'POST', body }); };
export const deleteExpenseInvoice = (request: Request, expenseId: string, invoiceId: string) => request<void>(`/api/admin/expenses/${expenseId}/invoices/${invoiceId}`, { method: 'DELETE' });
export const listDocumentTypes = (request: Request) => request<DocumentType[]>('/api/admin/document-types?includeInactive=true');
export const createDocumentType = (request: Request, body: Omit<DocumentType, 'id'>) => request<DocumentType>('/api/admin/document-types', { method: 'POST', body });
export const updateDocumentType = (request: Request, id: string, body: Omit<DocumentType, 'id'>) => request<DocumentType>(`/api/admin/document-types/${id}`, { method: 'PUT', body });
export const deleteDocumentType = (request: Request, id: string) => request<void>(`/api/admin/document-types/${id}`, { method: 'DELETE' });
export const listDocuments = (request: Request, filters: Record<string, string>) => request<ComplianceDocument[]>(`/api/admin/documents?${query(filters)}`);
export const getDocumentDashboard = (request: Request, filters: Record<string, string>) => request<DocumentDashboard>(`/api/admin/documents/dashboard?${query(filters)}`);
export const createDocument = (request: Request, body: DocumentInput) => request<ComplianceDocument>('/api/admin/documents', { method: 'POST', body });
export const updateDocument = (request: Request, id: string, body: DocumentInput) => request<ComplianceDocument>(`/api/admin/documents/${id}`, { method: 'PUT', body });
export const deleteDocument = (request: Request, id: string) => request<void>(`/api/admin/documents/${id}`, { method: 'DELETE' });
export const deleteDocuments = (request: Request, ids: string[]) => request<BulkDeleteResult>('/api/admin/documents/bulk-delete', { method: 'POST', body: { ids } });
export const previewAdministrativeImport = (request: Request, type: 'EXPENSE' | 'DOCUMENT', body: unknown) => request<AdministrativeImportPreview>(`/api/admin/${type === 'EXPENSE' ? 'expenses' : 'documents'}/import/preview`, { method: 'POST', body });
export const importAdministrativeWorkbook = (request: Request, type: 'EXPENSE' | 'DOCUMENT', body: unknown) => request<AdministrativeImportResult>(`/api/admin/${type === 'EXPENSE' ? 'expenses' : 'documents'}/import`, { method: 'POST', body });
