import type { ApiRequestOptions } from '@/lib/api/client';
import type { AttendanceDashboard, AttendanceDeleteResult, AttendanceIdentifier, AttendanceImportPreview, AttendanceImportResult, AttendanceShift, AttendanceSource, DailyAttendance, DeviceEmployeePushResult, EmployeeOption, ExportTemplate, ScheduleRule, Timesheet, WorkbookMapping, WorkbookPreview } from '../types/attendance';
type Request = <T>(path: string, options?: ApiRequestOptions) => Promise<T>;
export const getAttendanceDashboard = (request: Request, month: string) => request<AttendanceDashboard>(`/api/hr/attendance/dashboard?month=${month}`);
export const getTimesheet = (request: Request, month: string) => request<Timesheet>(`/api/hr/attendance/timesheet?month=${month}`);
export const listShifts = (request: Request) => request<AttendanceShift[]>('/api/hr/attendance/shifts?includeInactive=true');
export const listEmployees = (request: Request) => request<EmployeeOption[]>('/api/hr/attendance/employees');
export const listSources = (request: Request) => request<AttendanceSource[]>('/api/hr/attendance/sources');
export const createShift = (request: Request, body: unknown) => request<AttendanceShift>('/api/hr/attendance/shifts', { method: 'POST', body });
export const updateShift = (request: Request, id: string, body: unknown) => request<AttendanceShift>(`/api/hr/attendance/shifts/${id}`, { method: 'PUT', body });
export const deleteShift = (request: Request, id: string) => request<void>(`/api/hr/attendance/shifts/${id}`, { method: 'DELETE' });
export const assignShift = (request: Request, body: unknown) => request('/api/hr/attendance/assignments/bulk', { method: 'POST', body });
export const listSchedules = (request: Request) => request<ScheduleRule[]>('/api/hr/attendance/schedules');
export const createSchedule = (request: Request, body: unknown) => request<ScheduleRule>('/api/hr/attendance/schedules', { method: 'POST', body });
export const deleteSchedule = (request: Request, id: string) => request<void>(`/api/hr/attendance/schedules/${id}`, { method: 'DELETE' });
export const listExportTemplates = (request: Request) => request<ExportTemplate[]>('/api/hr/attendance/export-templates');
export const createExportTemplate = (request: Request, body: { name: string; filename: string; workbookBase64: string; mapping: WorkbookMapping }) => request<ExportTemplate>('/api/hr/attendance/export-templates', { method: 'POST', body });
export const updateExportTemplate = (request: Request, id: string, body: { name: string; mapping: WorkbookMapping }) => request<ExportTemplate>(`/api/hr/attendance/export-templates/${id}`, { method: 'PUT', body });
export const getExportTemplatePreview = (request: Request, id: string) => request<WorkbookPreview>(`/api/hr/attendance/export-templates/${id}/preview`);
export const deleteExportTemplate = (request: Request, id: string) => request<void>(`/api/hr/attendance/export-templates/${id}`, { method: 'DELETE' });
export const syncAmis = (request: Request, connectionId: string, fromDate: string, toDate: string, replaceExisting = false) => request('/api/hr/attendance/sync/amis', { method: 'POST', body: { connectionId, fromDate, toDate, replaceExisting } });
export const syncDevice = (request: Request, connectionId: string, fromDate: string, toDate: string, replaceExisting = false) => request('/api/hr/attendance/sync/device', { method: 'POST', body: { connectionId, fromDate, toDate, replaceExisting } });
export const deleteAttendanceData = (request: Request, sourceType: 'AMIS' | 'DEVICE' | 'IMPORT', connectionId: string | null, fromDate: string, toDate: string) => request<AttendanceDeleteResult>('/api/hr/attendance/data/delete', { method: 'POST', body: { sourceType, connectionId, fromDate, toDate } });
export const listAttendanceIdentifiers = (request: Request, connectionId: string) => request<AttendanceIdentifier[]>(`/api/hr/attendance/employee-identifiers?connectionId=${encodeURIComponent(connectionId)}`);
export const saveAttendanceIdentifier = (request: Request, body: { connectionId: string; externalAttendanceId: string; employeeId: string; sourceEmployeeCode: string | null; sourceEmployeeName: string | null }) => request<AttendanceIdentifier>('/api/hr/attendance/employee-identifiers', { method: 'PUT', body });
export const deleteAttendanceIdentifier = (request: Request, id: string) => request<void>(`/api/hr/attendance/employee-identifiers/${id}`, { method: 'DELETE' });
export const pushEmployeesToDevice = (request: Request, connectionId: string, employeeIds: string[]) => request<DeviceEmployeePushResult>('/api/hr/attendance/device-management/employees/push', { method: 'POST', body: { connectionId, employeeIds } });
export const adjustAttendance = (request: Request, recordId: string, body: unknown) => request<DailyAttendance>(`/api/hr/attendance/records/${recordId}`, { method: 'PATCH', body });
export const previewAttendanceImport = (request: Request, body: unknown) => request<AttendanceImportPreview>('/api/hr/attendance/import/preview', { method: 'POST', body });
export const importAttendanceWorkbook = (request: Request, body: unknown) => request<AttendanceImportResult>('/api/hr/attendance/import', { method: 'POST', body });
