'use client';

import { Eye, Table2, TriangleAlert, Upload, X } from 'lucide-react';
import { useState } from 'react';
import type { ApiRequestOptions } from '@/lib/api/client';
import GoogleSheetSourcePicker, { resolvedSheetFile } from '@/features/import-sources/components/google-sheet-source-picker';
import { importWorkWorkbook, previewWorkImport } from '../api/work-api';
import type { EmployeeOption, WorkImportInput, WorkImportPreview, WorkImportResult } from '../types/work';

type Request = <T>(path:string, options?:ApiRequestOptions)=>Promise<T>;
const fileBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});
const number=(value:number|null)=>value===null?'—':new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(value);

export default function WorkImportDialog({employees,defaultEmployeeId,month,request,close,imported}:{employees:EmployeeOption[];defaultEmployeeId:string;month:string;request:Request;close:()=>void;imported:(result:WorkImportResult,employeeId:string)=>Promise<void>}){
  const [employeeId,setEmployeeId]=useState(defaultEmployeeId||employees[0]?.id||'');
  const [file,setFile]=useState<File|null>(null);const [encoded,setEncoded]=useState('');
  const [sheetName,setSheetName]=useState('');const [replaceExisting,setReplaceExisting]=useState(false);
  const [preview,setPreview]=useState<WorkImportPreview|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');
  async function chooseFile(next:File|null){setFile(next);setPreview(null);setError('');setEncoded('');if(!next)return;if(!next.name.toLowerCase().endsWith('.xlsx')){setError('Chỉ chấp nhận file Excel .xlsx.');return;}if(next.size>10*1024*1024){setError('File Excel tối đa 10 MB.');return;}try{setEncoded(await fileBase64(next));}catch{setError('Không đọc được file đã chọn.');}}
  function useSheet(workbook:Parameters<typeof resolvedSheetFile>[0]){setFile(resolvedSheetFile(workbook));setEncoded(workbook.workbookBase64);if(workbook.sheetName)setSheetName(workbook.sheetName);setPreview(null);setError('');}
  function payload():WorkImportInput{return{employeeId,month,sheetName:sheetName.trim()||null,filename:file?.name??'',workbookBase64:encoded,replaceExisting};}
  async function inspect(){if(!employeeId||!encoded)return;setBusy('preview');setError('');try{setPreview(await previewWorkImport(request,payload()));}catch(cause){setPreview(null);setError(cause instanceof Error?cause.message:'Không xem trước được file Excel');}finally{setBusy('');}}
  async function commit(){if(!preview||preview.invalidRows)return;setBusy('import');setError('');try{const result=await importWorkWorkbook(request,payload());await imported(result,employeeId);close();}catch(cause){setError(cause instanceof Error?cause.message:'Không import được dữ liệu công việc');}finally{setBusy('');}}
  return <div className="nova-overlay"><section className="nova-dialog attendance-import-dialog work-import-dialog"><header><div><p>NHẬP DỮ LIỆU EXCEL</p><h2>Import công việc hàng ngày</h2><span>Nhận dạng form Cập nhật CV hàng ngày, xem trước rồi mới ghi dữ liệu.</span></div><button onClick={close}><X/></button></header><div className="nova-dialog-body">
    <GoogleSheetSourcePicker request={request} feature="WORK_PLAN" disabled={Boolean(busy)} onResolved={useSheet}/>
    <div className="work-import-controls"><label><span>Nhân viên nhận dữ liệu</span><select value={employeeId} onChange={event=>{setEmployeeId(event.target.value);setPreview(null);}}><option value="">Chọn nhân viên</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.employeeCode} · {employee.fullName} · {employee.businessUnitName}</option>)}</select></label><label><span>Tháng đích</span><input value={month} readOnly/></label><label><span>Tên sheet (không bắt buộc)</span><input value={sheetName} onChange={event=>{setSheetName(event.target.value);setPreview(null);}} placeholder="Tự tìm theo tháng, VD. Tháng 9.26"/></label><label><span>File Excel .xlsx</span><input type="file" accept=".xlsx" onChange={event=>void chooseFile(event.target.files?.[0]??null)}/></label><label className="work-import-replace"><input type="checkbox" checked={replaceExisting} onChange={event=>setReplaceExisting(event.target.checked)}/><span>Thay toàn bộ công việc hiện có của nhân viên trong tháng này</span></label></div>
    <div className="nova-info-note"><Table2/><span>Hệ thống đọc cột B–E và số lượng từng ngày ở G–AK. Bảng kết quả công thức phía dưới sheet sẽ không bị import lặp.</span></div>
    {error&&<div className="performance-error"><TriangleAlert/>{error}</div>}
    {file&&<div className="attendance-import-file"><Table2/><div><b>{file.name}</b><small>{(file.size/1024).toFixed(1)} KB</small></div><button className="nova-button primary" disabled={!employeeId||!encoded||busy==='preview'} onClick={()=>void inspect()}><Eye/>{busy==='preview'?'Đang kiểm tra…':'Xem trước dữ liệu'}</button></div>}
    {preview&&<section className="attendance-import-preview work-import-preview"><header><div><h3>Sheet “{preview.sheetName}” · {preview.month}</h3><p>{preview.totalRows} công việc · <b>{preview.validRows} hợp lệ</b> · <em>{preview.invalidRows} lỗi</em></p></div><span className={preview.invalidRows?'invalid':'valid'}>{preview.invalidRows?'Cần sửa file':'Sẵn sàng import'}</span></header>{preview.warnings.map(warning=><small className="attendance-import-warning" key={warning}>{warning}</small>)}<div className="attendance-import-table-wrap"><table><thead><tr><th>Dòng</th><th>Công tác</th><th>Chi tiết công việc</th><th>Định lượng</th><th>Hệ số</th><th>Số ngày có dữ liệu</th><th>MTD</th><th>Kiểm tra</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.rowNumber} className={row.valid?'':'invalid'}><td>{row.rowNumber}</td><td>{row.workGroup||'—'}</td><td><b>{row.title}</b><small>{row.itemType==='AD_HOC'?'Phát sinh':'Kế hoạch'}</small></td><td>{number(row.targetQuantity)}</td><td>{number(row.weight)}</td><td>{row.dailyEntries}</td><td>{number(row.completedQuantity)}</td><td>{row.valid?<em className="ok">Hợp lệ</em>:<em>{row.errors.join('; ')}</em>}</td></tr>)}</tbody></table></div></section>}
  </div><footer><button className="nova-button secondary" onClick={close}>Hủy</button><button className="nova-button primary" disabled={!preview||preview.invalidRows>0||busy==='import'} onClick={()=>void commit()}><Upload/>{busy==='import'?'Đang import…':`Import ${preview?.validRows??0} công việc`}</button></footer></section></div>;
}
